### ISSUE TITLE
Component UUID is not Written when Saving Edits to a Numbered Control Statement

### ISSUE THREAD

**Issue by hreineck** [EasyDynamics/oscal-rest-service#100]
When using the OSCAL Editor UI to edit the parameters or description of a numbered control statement (eg. AC-1.2), the `component-uuid` of the created `by-component` object is not set, leaving the field blank.
Per the OSCAL Schema `component-uuid` should be necessary for differentiating between descriptions pertaining to each component.

### Implementation Notes

This affects edits to the `statements` object under `control-implementation`. See the [OSCAL SSP Reference](https://pages.nist.gov/OSCAL/reference/latest/system-security-plan/json-reference/#/system-security-plan/control-implementation/implemented-requirements/statements):
`statements/by-components/component-uuid` is not being set.

**Comment by Bronstrom** [comment]
This is closed by https://github.com/EasyDynamics/oscal-react-library/pull/538
