### ISSUE TITLE
Pull Test Content From oscal-demo-content

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-rest-service#22]
~~We could consider publishing the `oscal-content` folder as a Maven artifact with a different classifier (perhaps `default-content`) that could be pulled along with the app jar as a default/testing artifact.~~

We could consider pulling from [oscal-demo-content](https://github.com/EasyDynamics/oscal-demo-content) as a default/testing artifact.

**Comment by rgauss** [comment]
This was partially done with the maven submodules in #34, but we likely want to consider an approach similar to #62 to dynamically download content from [oscal-demo-content](https://github.com/EasyDynamics/oscal-demo-content).

**Comment by laurelmay** [comment]
Did you have a general plan in mind for the implementation here? We can [download a ZIP](https://github.com/EasyDynamics/oscal-demo-content/archive/refs/heads/main.zip) of the repo but I am not entirely sure how we'd go about extracting it.

I also feel like using git submodules for that purpose might be a little messy but possibly another option?

**Comment by rgauss** [comment]
We could use [`maven-antrun-plugin`](https://maven.apache.org/plugins/maven-antrun-plugin/) for unzipping.

I have had issues in the past with keeping 'latest' git submodules up to date in the past, but that was quite a while ago.

**Comment by laurelmay** [comment]
Turns out there's an `unpack` option to the download plugin we've already used elsewhere! Had to [dig a bit](https://github.com/maven-download-plugin/maven-download-plugin/blob/master/src/main/java/com/googlecode/download/maven/plugin/internal/WGet.java#L122) to find the parameters that are available.
