### ISSUE TITLE
BUILD FAILURE

### ISSUE THREAD

**Issue by degenaro** [EasyDynamics/oscal-rest-service#76]
User error of some kind?

> mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] oscal-rest-service-parent                                          [pom]
[INFO] oscal-data-repository-commons                                      [jar]
[INFO] oscal-data-repository-commons-tests                                [jar]
[INFO] oscal-data-repository-file                                         [jar]
[INFO] oscal-object-service                                               [jar]
[INFO] oscal-rest-service-app                                             [jar]
[INFO] 
[INFO] -------------< com.easydynamics:oscal-rest-service-parent >-------------
[INFO] Building oscal-rest-service-parent 0.0.1-SNAPSHOT                  [1/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ oscal-rest-service-parent ---
[INFO] Deleting /home/degenaro/git/easy-dynamics/oscal-rest-service/target
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.2:check (validate) @ oscal-rest-service-parent ---
[WARNING] Old version of checkstyle detected. Consider updating to >= v8.30
[WARNING] For more information see: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ oscal-rest-service-parent ---
[INFO] Installing /home/degenaro/git/easy-dynamics/oscal-rest-service/pom.xml to /home/degenaro/.m2/repository/com/easydynamics/oscal-rest-service-parent/0.0.1-SNAPSHOT/oscal-rest-service-parent-0.0.1-SNAPSHOT.pom
[INFO] 
[INFO] -----------< com.easydynamics:oscal-data-repository-commons >-----------
[INFO] Building oscal-data-repository-commons 0.0.1-SNAPSHOT              [2/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ oscal-data-repository-commons ---
[INFO] Deleting /home/degenaro/git/easy-dynamics/oscal-rest-service/oscal-data-repository-commons/target
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.2:check (validate) @ oscal-data-repository-commons ---
[WARNING] Old version of checkstyle detected. Consider updating to >= v8.30
[WARNING] For more information see: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ oscal-data-repository-commons ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/degenaro/git/easy-dynamics/oscal-rest-service/oscal-data-repository-commons/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ oscal-data-repository-commons ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 10 source files to /home/degenaro/git/easy-dynamics/oscal-rest-service/oscal-data-repository-commons/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] oscal-rest-service-parent 0.0.1-SNAPSHOT ........... SUCCESS [  0.850 s]
[INFO] oscal-data-repository-commons ...................... FAILURE [  0.492 s]
[INFO] oscal-data-repository-commons-tests ................ SKIPPED
[INFO] oscal-data-repository-file ......................... SKIPPED
[INFO] oscal-object-service ............................... SKIPPED
[INFO] oscal-rest-service-app 0.0.1-SNAPSHOT .............. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.636 s
[INFO] Finished at: 2022-03-28T15:11:45-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project oscal-data-repository-commons: Fatal error compiling: invalid target release: 11 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :oscal-data-repository-commons

**Comment by laurelmay** [comment]
Thank you for taking the time to report this! Based on the error message, it seems that the Maven Compiler plugin was unable to specify Java 11 as a target release. Could you confirm which version of Java you're using by providing the output of:

```bash
java -version
```

As of today, building the project does require Java 11 (or I suppose more technically, a version of `javac` that can support `11` as an argument to `-source` and `-target`) ; if you're limited to using another version, we can definitely evaluate adding support for other releases (we have talked about investigating Java 17, though I am not sure if we've looked at Java 8). In the meantime, I will also update the README to document the dependency on Java 11.

**Comment by laurelmay** [comment]
Hi @degenaro! Have you had the opportunity to confirm which version of Java was in use during the `mvn clean install`? We have since added tests to ensure the library compiles on Java 11 and Java 17 to our CI pipeline; we also updated the version of our `maven-compiler-plugin` dependency. My hope is that a `mvn clean install` from the `develop` branch on Java 11 or newer would work for you now. Would you be able to give that a try?

**Comment by degenaro** [comment]
Sadly, I have an older version of java installed. Someday I'll upgrade and
give it a try...

Loou.

**Comment by laurelmay** [comment]
Thanks for taking the time to make a report and for your interest in the application! Unfortunately, we are using quite a few features introduced in Java 11. If your goal was to have a server built, you may find our [all-in-one container image](https://github.com/EasyDynamics/oscal-editor-deployment/tree/main/all-in-one) useful; this contains a live client and server which you can use to preview the application and interact with the API.

I think at this time, I am going to go ahead and close this issue. If you experience issues in the future compiling on Java 11 or newer, please feel free to open an issue here. And if you have any questions about the all-in-one image, we'd be happy to answer them on that repo!
